const products=[
{id:'letras',name:'Letras grandes personalizadas',price:10,priceText:'Desde 10 €',img:'assets/letras-1.jpeg',desc:'Inicial decorativa con nombre en relieve, impresa en 3D y disponible en varios colores.',options:'letters'},
{id:'bolas',name:'Bolas de Navidad de litofanía',price:5,priceText:'Desde 5 €',img:'assets/bolas.jpeg',desc:'Convierte tus fotos favoritas en un adorno navideño de litofanía.',options:'balls'},
{id:'fitness',name:'Llaveros fitness personalizados',price:null,priceText:'Consultar precio',img:'assets/fitness-1.jpeg',desc:'Llaveros deportivos impresos en 3D, personalizables con nombre, iniciales, logo o colores.',options:'fitness'},
{id:'padel',name:'Llaveros de pádel',price:5,priceText:'5 €',img:'assets/padel.jpeg',desc:'Mini pala de pádel impresa en 3D. Ligera, resistente y disponible en varios colores.',options:'padel'}];
let cart=JSON.parse(localStorage.getItem('mic-cart')||'[]');
const grid=document.querySelector('#productGrid');
products.forEach(p=>grid.insertAdjacentHTML('beforeend',`<article class="product"><img src="${p.img}" alt="${p.name}"><div class="product-body"><div class="product-top"><h3>${p.name}</h3><span class="price">${p.priceText}</span></div><p>${p.desc}</p><button onclick="openProduct('${p.id}')">Personalizar y añadir</button></div></article>`));
function openProduct(id){const p=products.find(x=>x.id===id);let fields='';if(p.options==='letters')fields=`<label>Tamaño</label><select id="optSize" onchange="updateModalPrice()"><option value="15 cm|10">15 cm — 10 €</option><option value="20 cm|15">20 cm — 15 €</option></select><label>Nombre</label><input id="optName" placeholder="Ej. Martina"><label>Color</label><input id="optColor" placeholder="Ej. rosa, azul, verde…">`;if(p.options==='balls')fields=`<label>Pack</label><select id="optSize" onchange="updateModalPrice()"><option value="1 bola|5">1 bola — 5 €</option><option value="4 bolas|18">4 bolas — 18 €</option></select><label>Notas sobre las fotos</label><input id="optName" placeholder="Las enviaremos después por WhatsApp">`;if(p.options==='fitness')fields=`<label>Diseño / personalización</label><input id="optName" placeholder="Logo, iniciales, colores…"><p><b>Precio:</b> lo confirmaremos por WhatsApp.</p>`;if(p.options==='padel')fields=`<label>Color o detalles</label><input id="optName" placeholder="Indica tu preferencia">`;
document.querySelector('#modalContent').innerHTML=`<div class="detail"><img src="${p.img}" alt="${p.name}"><div><span class="eyebrow">MADE IN CANILES</span><h2>${p.name}</h2><p>${p.desc}</p>${fields}<button class="add" onclick="addToCart('${p.id}')">Añadir al carrito <span id="modalPrice">${p.price===null?'': '· '+p.price+' €'}</span></button></div></div>`;document.querySelector('#modal').classList.remove('hidden');document.querySelector('#overlay').classList.remove('hidden')}
function updateModalPrice(){const s=document.querySelector('#optSize');if(!s)return;const price=s.value.split('|')[1];document.querySelector('#modalPrice').textContent='· '+price+' €'}
function addToCart(id){const p=products.find(x=>x.id===id);let price=p.price,detail=[];const size=document.querySelector('#optSize');if(size){const [label,val]=size.value.split('|');detail.push(label);price=Number(val)}const name=document.querySelector('#optName');if(name?.value)detail.push(name.value);const color=document.querySelector('#optColor');if(color?.value)detail.push('Color: '+color.value);cart.push({id,name:p.name,price,detail:detail.join(' · ')});saveCart();closeModal();openCart()}
function saveCart(){localStorage.setItem('mic-cart',JSON.stringify(cart));renderCart()}
function renderCart(){document.querySelector('#cartCount').textContent=cart.length;const box=document.querySelector('#cartItems');if(!cart.length)box.innerHTML='<p>Tu carrito está vacío.</p>';else box.innerHTML=cart.map((x,i)=>`<div class="cart-item"><strong>${x.name}</strong><small>${x.detail||'Sin detalles adicionales'}</small><div>${x.price==null?'Precio a consultar':x.price+' €'}</div><button class="remove" onclick="removeItem(${i})">Eliminar</button></div>`).join('');const known=cart.filter(x=>x.price!=null).reduce((a,b)=>a+b.price,0);const unknown=cart.some(x=>x.price==null);document.querySelector('#cartTotal').textContent=(known?known+' €':'')+(unknown?(known?' + consultar':'A consultar'):'')}
function removeItem(i){cart.splice(i,1);saveCart()}
function closeModal(){document.querySelector('#modal').classList.add('hidden');if(!document.querySelector('#cart').classList.contains('open'))document.querySelector('#overlay').classList.add('hidden')}
function openCart(){document.querySelector('#cart').classList.add('open');document.querySelector('#overlay').classList.remove('hidden')}
function closeCart(){document.querySelector('#cart').classList.remove('open');document.querySelector('#overlay').classList.add('hidden')}
document.querySelector('#cartBtn').onclick=openCart;document.querySelector('#closeCart').onclick=closeCart;document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#overlay').onclick=()=>{closeModal();closeCart()};document.querySelector('#whatsappBtn').onclick=()=>{if(!cart.length)return alert('Añade algún producto al carrito.');let total=cart.filter(x=>x.price!=null).reduce((a,b)=>a+b.price,0);let msg='Hola, quiero realizar un pedido en Made In Caniles:%0A%0A'+cart.map(x=>`• ${x.name}${x.detail?' — '+x.detail:''}${x.price!=null?' — '+x.price+' €':' — precio a consultar'}`).join('%0A')+`%0A%0A${total?'Total conocido: '+total+' €%0A':''}¿Me confirmáis disponibilidad y los siguientes pasos?`;window.open('https://wa.me/34673596200?text='+msg,'_blank')};document.querySelector('#year').textContent=new Date().getFullYear();renderCart();
